### ISSUE TITLE
inline math regex

### ISSUE THREAD

**Issue by tessus** [CalebJohn/joplin-math-mode#12]
Come to think of it, I'm wondering whether the positive lookahead at the end should be replaced by a test for what is allowed instead of checking for what is not.

Because anything after `=`, except a `(`, `space`, a digit and character, is invalid, correct? Unless I'm missing other functionality for inline math.

All the following lines would be throwing errors:

```
=<
=)
=#
=@
='
=!
=?
=&
and so on
```

Of course we can add all the characters to the negated character class, but wouldn't it be easier to test for what is allowed?

What do you think?

**Comment by CalebJohn** [comment]
I'm glad you brought this up, I made a note for myself to look into this after I saw your pull request.

> Because anything after =, except a (, space, a digit and character, is invalid, correct? Unless I'm missing other functionality for inline math.

The only other thing I know about is vectors/matrices, so the `[` character should be supported.

The reason I have hesitate with your solution is because the plugin simply passes everything past the equals sign to mathjs, and I'm not entirely certain what the extent of mathjs functionality is.

With that said, the way I see it, there are 2 options. My preferred path is what you have proposed, check for valid characters in the regex. The other path is to check for a value error in mathjs and not display anything in that case. The reason I bring up the second option is just in case you have a reason that I'm missing that might make it preferable. 

If you have no objections, I'll fix the regex in the way you suggest (probably tomorrow).

**Comment by tessus** [comment]
I also like option 1 better, but there might be one advantage of option 2: in case new functionality were to be added to mathjs, it would be automatically supported without having to change the regex.

On the other side, in certain situations it is better not to automatically support new stuff. Also what would happen if there was a legitimate value error.
It's hard to say. I would probably go with option 1 for now. It can always be changed later.

**Comment by tessus** [comment]
That should do it: `^(\+|\-)?=(?= *[0-9a-zA-Z\[\(])`

**Comment by tessus** [comment]
Time for my beauty sleep. ttyl.

**Comment by CalebJohn** [comment]
Thanks @tessus . I appreciate you sacrificing some beauty sleep over this :)
