### ISSUE TITLE
notation

### ISSUE THREAD

**Issue by tessus** [CalebJohn/joplin-math-mode#13]
There are currently only 2 notations and they are not really usable if you want an exact result.

e.g. I was calculating GBs to bytes and this is what happened:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/223439/115312827-178c9480-a140-11eb-8b80-b3d102680a15.png">

Is there a way to allow normal notation? In many calculators the result is only shown in exponential notation when reaching really big or small numbers. 15 digits should be ok for any calculator unless you have one from the 90's.

**Comment by tessus** [comment]
Also, it would be awesome, if it were posible to copy the result.

**Comment by CalebJohn** [comment]
Thanks for pointing this out, it actually is possible to change to a fixed notation, but I haven't exposed it in the settings menu (yet). I'll make it available on the next release. I'll also change the behaviour of auto so that it changes to exponential later (I can also make this configurable).
Take a look at this example of fixed notation (you can also add `global: true` if you want the setting to apply for the entire note).
![image](https://user-images.githubusercontent.com/2179547/115494391-c6a19c80-a222-11eb-8d2e-63f6246eb98a.png)

**Comment by tessus** [comment]
Ah, cool. I didn't know that `notation: fixed` was possible. I remember you added options, but missed the `fixed`.

**Comment by tessus** [comment]
If you want we can close this, unless you want to keep it open as a reminder.

**Comment by CalebJohn** [comment]
Fixed in faf8800
