### ISSUE TITLE
Calculation not correct

### ISSUE THREAD

**Issue by philippludwig** [CalebJohn/joplin-math-mode#23]
![image](https://github.com/CalebJohn/joplin-math-mode/assets/3770792/91e84977-b35b-4aba-9753-cbbbb9cf64e8)

![image](https://github.com/CalebJohn/joplin-math-mode/assets/3770792/90fd4174-25b0-4ae3-9a14-39e45e443172)

See screenshots. I just installed this and tested it with some random numbers. Not sure what’s going on here.

**Comment by CalebJohn** [comment]
This is how the calculations should look by default
![image](https://github.com/CalebJohn/joplin-math-mode/assets/2179547/6ebfbce3-d5d2-4129-b11a-f43bf9c4ef6b)

But it looks like you've changed the default precision from 8 down to 3, resulting in some rounding
![image](https://github.com/CalebJohn/joplin-math-mode/assets/2179547/7c527bc4-4a40-4495-9456-0636fa0e8c10)

It's been awhile since I wrote this plugin, but I probably didn't realize that the precision option worked this way when I implemented it. I assumed (probably as you did) that it is number of decimal places. I will push out a fix for this right away, I will make it clear that this option is "significant digits" and I'll change the default behaviour so that it switches to exponential notation when exceeding that many digits.

Sadly the library (math.js) that underpins this plugin does not support setting a maximum number of decimal places, so that will likely not be supported here. You can used the "Fixed" notation if you need a specific number of decimal points.

**Comment by philippludwig** [comment]
Indeed I changed the precision; but I did not think that this had anything to do with it. Thanks for the quick reply!
