### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by hexadecagram** [CalebJohn/joplin-math-mode#7]
I could really use LaTeX support in this plugin. Being a perpetual student of science and engineering, a robust note-taking app is right up my alley.

Unfortunately, my time is extremely thin so while I cannot contribute any code initially, I can at least get the ball rolling with this idea: [MathJax](http://mathjax.org). I know for a fact that it works well because [Typora](http://typora.io) uses it. Typora, however, is "just" an editor, and not a note management app like Joplin, whose strengths and potential I perceive to be in organization, indexing, and cross-referencing.

Fortunately, I can ⌘E and fire up Typora from Joplin but wide adoption of open standards is a good thing and MathJax exports to MathML, which is indeed an open standard.

Please have a look at Typora and MathJax and see if they can expose a means of bringing LaTeX to Joplin. I will do the same as time goes on, contribute what I can when I can, and hope that you will include my patches.

**Comment by CalebJohn** [comment]
Hi @hexadecagram 

Thanks for your interest in my plugin! I feel like there might be some confusion here on your part about what the purpose of this plugin is. This plugin allows Joplin user's to type math in a regular expression syntax (not latex) and see the result (maybe I should have called this plugin joplin-calculator).

Joplin already [supports latex math using the katex library](https://joplinapp.org/markdown/#math-notation). Katex is a library that is almost identical to MathJax, but apparently runs faster. 

With that in mind, I'm not exactly sure what functionality you're requesting. Feel free to follow up with more info about what you want, but I'd recommend you to make the request on the [forum](https://discourse.joplinapp.org/) because I suspect what you're requesting isn't in the scope of this plugin and you might find someone on the forum with an interest in picking up what you propose.

**Comment by hexadecagram** [comment]
Hi @CalebJohn 

I created this issue in response to [this thread](https://discourse.joplinapp.org/t/compatibility-with-latex/5144), [this thread](https://discourse.joplinapp.org/t/replace-katex-with-mathjax/2561), and the ["ideas" section of this very plugin's Roadmap.](https://github.com/CalebJohn/joplin-math-mode#ideas)

It seems that in the first thread, the idea of having LaTeX support in Joplin at all was initially shot down (yet the KaTeX plugin was already available). I think this was due to a misunderstanding by laurent, which blossomed into some confusion and frustration about the difference between LaTeX and KaTeX (myself included).

The real problem with KaTeX is that it implements a non-standard form of LaTeX where certain environments and possibly elements are stripped from the distribution (eqnarray immediately comes to mind and evidently equation itself is also subject), presumably to give the speed that is desired. That's all well and good for people that want that speed but for those of us that want (or need) full LaTeX support, this simply will not do. MathJax is a step toward fulfilling that need.

It seems you are correct that joplin-math-mode is not the way to get MathJax into Joplin; my mistake and I apologize for misposting. However, I for one would very much appreciate if an option to switch out KaTeX for MathJax could be worked into Joplin. It seems there is some resistance to having one, but I see no good reason why this should be.

I tend to think that the best way to get such things "approved" is to just code and submit them rather than argue with project leaders. And if I had the time to do it right now I would. About the only thing I could do right now is post a response to the thread on the Joplin Discourse. And by the way, you're not being obtuse at all. MathJax absolutlely needs to be part of Joplin.

**Comment by CalebJohn** [comment]
Moving this discussion to the forum would be best. I'm not the owner of the Joplin project and don't have much say in these matters.

I look forward to seeing this discussion continue on the forum.

Btw, I know your time is limited, but Joplin recently added support for a plugin system. This plugin system allows for extension to the markdown-it renderer. It shouldn't take too long for you to write a plugin that allows mathjax in code blocks with the language specified as mathjax (there are examples in the Joplin repository for how to do this).
